import React, { useEffect, useMemo, useRef, useState } from 'react';
import { details, imageUrl, popularMovies, popularTv, searchMulti, seasons, trending } from './services/tmdb.js';
import { addHistory, clearHistory, loadStore, setProgress, toggleMyList } from './storage/store.js';

const typeName=x=>x.media_type==='tv'||x.first_air_date?'tv':'movie';
function Card({item,onSelect}){return <button className="card" onClick={()=>onSelect(item)}><div className="poster"><img src={imageUrl(item.poster_path)} alt=""/><span className="posterGlow"/></div><span>{item.title||item.name}</span><small>{(item.release_date||item.first_air_date||'').slice(0,4)} · {item.vote_average?`${item.vote_average.toFixed(1)} ★`:'New'}</small></button>}
const KEYBOARD_ROWS=[['1','2','3','4','5','6','7','8','9','0'],['Q','W','E','R','T','Y','U','I','O','P'],['A','S','D','F','G','H','J','K','L'],['Z','X','C','V','B','N','M'],['SPACE','BACKSPACE','CLEAR','SEARCH']];
function VirtualKeyboard({value,onChange,onSearch,onClose}){const add=key=>{if(key==='SPACE')onChange(value+' ');else if(key==='BACKSPACE')onChange(value.slice(0,-1));else if(key==='CLEAR')onChange('');else if(key==='SEARCH')onSearch();else onChange(value+key)};return <div className="virtualKeyboard" role="dialog" aria-label="On-screen keyboard"><div className="keyboardHeader"><div><span className="eyebrow">TV SEARCH</span><strong>Type with your controller or keyboard</strong></div><button className="keyboardClose" onClick={onClose}>✕ Close</button></div><div className="keyboardRows">{KEYBOARD_ROWS.map((row,i)=><div className={`keyboardRow row-${i}`} key={i}>{row.map(key=><button key={key} data-virtual-key={key} className={key.length>1?'keyboardSpecial':''} onClick={()=>add(key)}>{key==='BACKSPACE'?'⌫':key==='SPACE'?'Space':key==='CLEAR'?'Clear':key==='SEARCH'?'Search ↵':key}</button>)}</div>)}</div></div>}
function ExitConfirm({onCancel,onConfirm}){const cancelRef=useRef(null);useEffect(()=>{requestAnimationFrame(()=>cancelRef.current?.focus());const onKey=e=>{if(e.key==='Escape')onCancel();if(e.key==='Enter')onConfirm()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[onCancel,onConfirm]);return <div className="exitOverlay" role="dialog" aria-modal="true" aria-labelledby="exit-title"><div className="exitDialog"><div className="exitIcon">×</div><p className="eyebrow">EXIT MOVIE+</p><h2 id="exit-title">Close the application?</h2><p>Are you sure you want to exit Movie+?</p><div className="exitActions"><button ref={cancelRef} className="secondary" onClick={onCancel}>No, stay</button><button className="primary" onClick={onConfirm}>Yes, close</button></div><small>Use A to select · B to cancel</small></div></div>}

function App(){
 const [page,setPage]=useState('home'),[items,setItems]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[player,setPlayer]=useState(null),[error,setError]=useState(''),[store,setStore]=useState(loadStore()),[loading,setLoading]=useState(true),[keyboardOpen,setKeyboardOpen]=useState(false),[playerBackNotice,setPlayerBackNotice]=useState(false),[exitConfirm,setExitConfirm]=useState(false);const searchRef=useRef(null),playerBackTimer=useRef(null);
 const refreshHome=async()=>{setLoading(true);setError('');try{const data=await trending();setItems(data.results||[])}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{refreshHome()},[]);
 useEffect(()=>{const focusKeyboardFromController=()=>{setExitConfirm(false);setKeyboardOpen(true);requestAnimationFrame(()=>document.querySelector('[data-virtual-key]')?.focus())};const onKeyboard=e=>{if(e.ctrlKey||e.altKey||e.metaKey)return;if(e.key==='Escape'){if(keyboardOpen)setKeyboardOpen(false);return}if(e.key.length===1&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){setQuery(q=>q+e.key);setKeyboardOpen(true);requestAnimationFrame(()=>{searchRef.current?.focus();searchRef.current?.setSelectionRange?.(searchRef.current.value.length,searchRef.current.value.length)})}};window.addEventListener('controllersearchactivate',focusKeyboardFromController);window.addEventListener('keydown',onKeyboard);return()=>{window.removeEventListener('controllersearchactivate',focusKeyboardFromController);window.removeEventListener('keydown',onKeyboard)}},[keyboardOpen]);
 useEffect(()=>{const onBack=()=>{if(exitConfirm)return;if(player){if(playerBackTimer.current){clearTimeout(playerBackTimer.current);playerBackTimer.current=null;setPlayerBackNotice(false);setPlayer(null);setPage('home');return}setPlayerBackNotice(true);playerBackTimer.current=setTimeout(()=>{playerBackTimer.current=null;setPlayerBackNotice(false)},1400);return}if(selected){setSelected(null);return}if(page!=='home'){setPage('home');setKeyboardOpen(false);return}setKeyboardOpen(false);setExitConfirm(true)};window.addEventListener('controllerback',onBack);return()=>{window.removeEventListener('controllerback',onBack);if(playerBackTimer.current)clearTimeout(playerBackTimer.current)}},[player,selected,page,exitConfirm]);
 async function navigate(next){setExitConfirm(false);setPage(next);setSelected(null);setPlayer(null);setKeyboardOpen(false);setError('');if(next==='home')return refreshHome();if(next==='mylist'){setItems(loadStore().myList);setLoading(false);return}if(next==='history'){setItems(loadStore().history);setLoading(false);return}setLoading(true);try{setItems(next==='movies'?(await popularMovies()).results:(await popularTv()).results)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function select(item){setError('');try{const full=await details(typeName(item),item.id);const updated=addHistory(full,'details');setStore(updated);setSelected(full)}catch(e){setError(e.message)}}
 async function search(e){e?.preventDefault?.();if(!query.trim())return refreshHome();setKeyboardOpen(false);setLoading(true);setError('');setPage('search');setSelected(null);setPlayer(null);try{setItems((await searchMulti(query.trim())).results.filter(x=>['movie','tv'].includes(x.media_type)))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function openPlayer(item,episode=null){const type=item.title?'movie':'tv';const url=type==='movie'?`https://www.vidking.net/embed/movie/${item.id}?autoplay=true&color=d6ad54`:`https://www.vidking.net/embed/tv/${item.id}/${episode?.season_number||1}/${episode?.episode_number||1}?autoplay=true&color=d6ad54`;const updated=addHistory(item,'play');setStore(updated);setPage('player');setPlayer({item,type,url,episode});setSelected(null);setPlayerBackNotice(false);try{await window.electronAPI?.enterFullscreen?.()}catch{}}
 const hero=useMemo(()=>items[0],[items]),listed=selected||player?[]:items;
 const confirmExit=()=>{setExitConfirm(false);if(window.electronAPI?.quitApp){window.electronAPI.quitApp();return}window.close()};
 return <div className="app">{!player&&<header className="topbar"><button className="brand" onClick={()=>navigate('home')} aria-label="Home"><span className="brandMark">M</span><span className="brandText">MOVIE</span><b>+</b></button><nav aria-label="Primary navigation">{['home','movies','tv','mylist','history'].map(x=><button key={x} className={page===x?'active':''} onClick={()=>navigate(x)}>{x==='tv'?'Series':x==='mylist'?'My List':x==='history'?'History':x[0].toUpperCase()+x.slice(1)}</button>)}</nav><form onSubmit={search} className="search"><span>⌕</span><input ref={searchRef} value={query} onClick={()=>{setKeyboardOpen(true);requestAnimationFrame(()=>document.querySelector('[data-virtual-key]')?.focus())}} onChange={e=>setQuery(e.target.value)} placeholder="Search movies & series"/><button type="submit" aria-label="Search">↵</button></form></header>}
 <main>{error&&<div className="error">{error}</div>}{player?<PlayerView player={player} store={store} setStore={setStore} onClose={()=>{setPlayer(null);setPage('home')}}/>:selected?<DetailsView item={selected} store={store} setStore={setStore} onBack={()=>setSelected(null)} onPlay={()=>openPlayer(selected)} onEpisodePlay={ep=>openPlayer(selected,ep)}/>:<>
 {hero&&page==='home'&&<section className="hero" style={{backgroundImage:`linear-gradient(90deg,#07080b 8%,rgba(7,8,11,.82) 42%,rgba(7,8,11,.15) 100%),url(${imageUrl(hero.backdrop_path,'original')})`}}><div><p className="eyebrow">✦ TRENDING THIS WEEK</p><h1>{hero.title||hero.name}</h1><p>{hero.overview}</p><div className="heroActions"><button className="primary" onClick={()=>select(hero)}>View Details</button><button className="ghost" onClick={()=>openPlayer(hero)}>▶ Play Now</button></div></div></section>}
 <section className="content"><div className="sectionTitle"><div><p className="eyebrow">{page==='history'?'YOUR ACTIVITY':'DISCOVER'}</p><h2>{page==='mylist'?'My List':page==='history'?'Recently Viewed':page==='search'?`Results for “${query}”`:page==='movies'?'Popular Movies':page==='tv'?'Popular Series':'Trending Now'}</h2></div><span>{items.length} titles</span>{page==='history'&&items.length>0&&<button className="clearBtn" onClick={()=>{const next=clearHistory();setStore(next);setItems([])}}>Clear History</button>}</div>{loading?<div className="loading"><i/> Loading your library…</div>:listed.length?<div className="grid">{listed.map(item=><Card key={`${item.key||item.media_type||typeName(item)}-${item.id}`} item={item} onSelect={select}/>)}</div>:<div className="empty"><strong>{page==='history'?'Your history is empty':'Nothing to show here.'}</strong><span>{page==='history'?'Movies and series you open will appear here.':'Try another section or search for something new.'}</span></div>}</section>
 {Object.values(store.progress).length>0&&page==='home'&&<section className="content"><div className="sectionTitle"><div><p className="eyebrow">PICK UP WHERE YOU LEFT OFF</p><h2>Continue Watching</h2></div></div><div className="progressList">{Object.values(store.progress).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,8).map((p,i)=><button key={i} onClick={()=>openPlayer(p)}><img src={imageUrl(p.poster_path,'w342')}/><span>{p.title||p.name}</span><small>{p.seconds?`${Math.floor(p.seconds/60)} min watched`:'Resume'}</small></button>)}</div></section>}
 {store.history.length>0&&page==='home'&&<section className="content"><div className="sectionTitle"><div><p className="eyebrow">RECENTLY VISITED</p><h2>History</h2></div><button className="textBtn" onClick={()=>navigate('history')}>See all →</button></div><div className="historyStrip">{store.history.slice(0,6).map(item=><button key={item.key} onClick={()=>select(item)}><img src={imageUrl(item.poster_path,'w342')}/><div><strong>{item.title||item.name}</strong><small>{item.kind==='play'?'Played':'Viewed'} · {new Date(item.visitedAt).toLocaleDateString()}</small></div></button>)}</div></section>}
 </>}</main>{playerBackNotice&&<div className="playerBackNotice" role="status"><strong>Press B again to go back</strong><span>Press B twice to exit the player</span></div>}{keyboardOpen&&!player&&<VirtualKeyboard value={query} onChange={setQuery} onSearch={()=>search()} onClose={()=>setKeyboardOpen(false)}/>} {exitConfirm&&<ExitConfirm onCancel={()=>setExitConfirm(false)} onConfirm={confirmExit}/>}</div>;
}

function DetailsView({item,store,setStore,onBack,onPlay,onEpisodePlay}){const type=item.title?'movie':'tv';const listed=store.myList.some(x=>x.key===`${type}-${item.id}`);const[seasonList,setSeasonList]=useState([]),[seasonNumber,setSeasonNumber]=useState(1),[episodes,setEpisodes]=useState([]),[seasonLoading,setSeasonLoading]=useState(false),[seasonError,setSeasonError]=useState('');useEffect(()=>{if(type!=='tv')return;const list=(item.seasons||[]).filter(s=>s.season_number>=0);setSeasonList(list);const first=list.find(s=>s.season_number>0)||list[0];if(first)setSeasonNumber(first.season_number)},[item,type]);useEffect(()=>{if(type!=='tv'||!seasonNumber)return;let cancelled=false;setSeasonLoading(true);setSeasonError('');seasons(item.id,seasonNumber).then(data=>{if(!cancelled)setEpisodes(data.episodes||[])}).catch(e=>{if(!cancelled)setSeasonError(e.message)}).finally(()=>{if(!cancelled)setSeasonLoading(false)});return()=>{cancelled=true}},[item.id,seasonNumber,type]);return <section className="details"><button className="back" onClick={onBack}>← Back</button><div className="detailHero" style={{backgroundImage:`linear-gradient(90deg,#07080b 10%,rgba(7,8,11,.84) 45%,rgba(7,8,11,.08)),url(${imageUrl(item.backdrop_path,'original')})`}}><div className="detailInfo"><p className="eyebrow">{type.toUpperCase()} · {item.release_date||item.first_air_date||'—'}</p><h1>{item.title||item.name}</h1><p>{item.overview}</p><div className="actions"><button className="primary" onClick={onPlay}>▶ Play Now</button><button className="secondary" onClick={()=>setStore(toggleMyList({...item,type}))}>{listed?'✓ In My List':'+ My List'}</button></div><div className="meta">{item.vote_average?.toFixed(1)} ★ &nbsp; {item.runtime?`${item.runtime} min`:type==='tv'?`${item.number_of_seasons||seasonList.length} Seasons`:'Movie'}</div></div></div>{type==='tv'&&<section className="episodeSection"><div className="episodeHeader"><div><p className="eyebrow">WATCH SERIES</p><h2>Seasons & Episodes</h2></div><div className="seasonPicker" role="listbox" aria-label="Select season">{seasonList.map(s=><button key={s.id||s.season_number} className={seasonNumber===s.season_number?'active':''} onClick={()=>setSeasonNumber(s.season_number)}>{s.name||`Season ${s.season_number}`}<small>{s.episode_count||0} episodes</small></button>)}</div></div>{seasonError&&<div className="error">{seasonError}</div>}{seasonLoading?<div className="loading"><i/> Loading episodes…</div>:<div className="episodeList">{episodes.map(ep=><button className="episodeCard" key={ep.id} onClick={()=>onEpisodePlay(ep)}><div className="episodeThumb">{ep.still_path?<img src={imageUrl(ep.still_path,'w500')} alt=""/>:<span>{String(ep.episode_number).padStart(2,'0')}</span>}<b>▶</b></div><div className="episodeInfo"><strong>{ep.episode_number}. {ep.name}</strong><small>{ep.air_date||'—'}{ep.runtime?` · ${ep.runtime} min`:''}</small><p>{ep.overview||'No episode description available.'}</p></div></button>)}</div>}</section>}</section>}
function PlayerView({player,store,setStore,onClose}){const startedAt=useRef(Date.now()),frameRef=useRef(null);useEffect(()=>{window.electronAPI?.enterFullscreen?.().catch?.(()=>{});const focusTimer=setTimeout(()=>frameRef.current?.focus(),100),timer=setInterval(()=>{const elapsed=(Date.now()-startedAt.current)/1000;if(elapsed>2)setStore(setProgress(player.item,elapsed))},10000);return()=>{clearTimeout(focusTimer);clearInterval(timer)}},[player.item,setStore]);return <section className="playerPage" tabIndex="-1"><div className="playerFullscreenStage"><iframe ref={frameRef} title="VidKing Player" src={player.url} allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowFullScreen tabIndex="0" onLoad={()=>frameRef.current?.focus()}/></div></section>}
export default App;