const BUTTONS = Object.freeze({ A: 0, B: 1, X: 2, Y: 3, LB: 4, RB: 5, LT: 6, RT: 7, SELECT: 8, START: 9, LS: 10, RS: 11, UP: 12, DOWN: 13, LEFT: 14, RIGHT: 15 });
const KEY_BY_BUTTON = { [BUTTONS.UP]:'ArrowUp', [BUTTONS.DOWN]:'ArrowDown', [BUTTONS.LEFT]:'ArrowLeft', [BUTTONS.RIGHT]:'ArrowRight', [BUTTONS.A]:'Enter', [BUTTONS.X]:'Space', [BUTTONS.Y]:'KeyF', [BUTTONS.LB]:'PageUp', [BUTTONS.RB]:'PageDown', [BUTTONS.SELECT]:'Escape', [BUTTONS.START]:'Enter', [BUTTONS.LS]:'KeyM', [BUTTONS.RS]:'KeyF' };
let activePad=null, previous=[], lastAction=new Map(), lastAxis={x:0,y:0}, statusEl, controllerMode=false;
const BUTTON_REPEAT_MS=420;
const AXIS_DEADZONE=0.28;
const MOUSE_MAX_STEP=9.5;
const MOUSE_ACCELERATION=2.15;
function isPlayer(){return !!document.querySelector('.playerPage')}
function isSearchField(){return !!document.activeElement?.matches?.('.search input')}
function setControllerCursorHidden(hidden){controllerMode=hidden;document.documentElement.classList.toggle('controller-active',hidden)}
function emitControllerActivity(detail={}){window.dispatchEvent(new CustomEvent('controlleractivity',{detail:{controllerId:activePad?.id||'Gamepad',...detail}}))}
function setStatus(text,ok=true){if(!statusEl){statusEl=document.createElement('div');statusEl.id='controller-status';Object.assign(statusEl.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'99999',padding:'9px 13px',borderRadius:'10px',font:'600 12px system-ui,sans-serif',color:'#eee',background:'rgba(10,11,14,.88)',border:'1px solid rgba(214,173,84,.35)',boxShadow:'0 8px 25px rgba(0,0,0,.35)',pointerEvents:'none',backdropFilter:'blur(12px)'});document.body.appendChild(statusEl)}statusEl.textContent=text;statusEl.style.borderColor=ok?'rgba(214,173,84,.55)':'rgba(255,100,100,.45)';statusEl.style.opacity='1';clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>{if(statusEl)statusEl.style.opacity='.45'},1800)}
function focusable(){return [...document.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex="0"]')].filter(el=>el.offsetParent!==null&&!el.closest('[aria-hidden="true"]'))}
function moveFocus(direction){const els=focusable(),current=document.activeElement;if(!current||!els.includes(current)){(els[0]||document.body).focus?.();return}const a=current.getBoundingClientRect(),ax=a.left+a.width/2,ay=a.top+a.height/2;let best=null,bestScore=Infinity;for(const el of els){if(el===current)continue;const r=el.getBoundingClientRect(),bx=r.left+r.width/2,by=r.top+r.height/2,dx=bx-ax,dy=by-ay,forward=direction==='left'?-dx:direction==='right'?dx:direction==='up'?-dy:dy;if(forward<=8)continue;const side=direction==='left'||direction==='right'?Math.abs(dy):Math.abs(dx),score=forward+side*2.2;if(score<bestScore){bestScore=score;best=el}}if(best){best.focus();best.scrollIntoView({block:'nearest',inline:'nearest'})}}
function dispatchKey(key){const target=document.activeElement||document.body;target.dispatchEvent(new KeyboardEvent('keydown',{key,code:key,bubbles:true,cancelable:true}))}
function movePlayerMouse(axisX,axisY){const magnitude=Math.hypot(axisX,axisY);if(magnitude<.001)return;const curved=Math.pow(Math.min(1,magnitude),MOUSE_ACCELERATION),step=Math.min(MOUSE_MAX_STEP,.65+(MOUSE_MAX_STEP-.65)*curved);window.electronAPI?.moveControllerMouse?.((axisX/magnitude)*step,(axisY/magnitude)*step)?.catch?.(()=>{})}
function clickPlayerMouse(){window.electronAPI?.clickControllerMouse?.()?.catch?.(()=>{})}
function action(index){emitControllerActivity({button:index,key:KEY_BY_BUTTON[index]||null});if(!isPlayer())setControllerCursorHidden(true);if(isPlayer()){if(index===BUTTONS.A)return clickPlayerMouse();if(index===BUTTONS.B||index===BUTTONS.SELECT)return dispatchKey('Escape');return}const key=KEY_BY_BUTTON[index];if(!key)return;if(index===BUTTONS.A&&isSearchField()){window.dispatchEvent(new CustomEvent('controllersearchactivate'));return}if(index===BUTTONS.B||index===BUTTONS.SELECT)return dispatchKey('Escape');if(index===BUTTONS.UP)return moveFocus('up');if(index===BUTTONS.DOWN)return moveFocus('down');if(index===BUTTONS.LEFT)return moveFocus('left');if(index===BUTTONS.RIGHT)return moveFocus('right');if([BUTTONS.A,BUTTONS.X,BUTTONS.Y,BUTTONS.START].includes(index)){const el=document.activeElement;if(el&&typeof el.click==='function')el.click()}}
function pressed(pad,index){const b=pad.buttons[index];return !!b&&(b.pressed||b.value>.5)}
function shouldRepeat(index,now){const last=lastAction.get(index)||0;if(now-last<BUTTON_REPEAT_MS)return false;lastAction.set(index,now);return true}
function poll(){const pads=navigator.getGamepads?navigator.getGamepads():[],pad=activePad&&pads[activePad.index]?pads[activePad.index]:[...pads].find(Boolean);if(pad&&(!activePad||activePad.index!==pad.index)){activePad={index:pad.index,id:pad.id};previous=[];lastAction.clear();setStatus(`🎮 Controller connected · ${pad.id||'Gamepad'}`);emitControllerActivity({connected:true})}if(!pad){if(activePad)setControllerCursorHidden(false);activePad=null;requestAnimationFrame(poll);return}const now=performance.now();let touched=false;for(let i=0;i<pad.buttons.length;i++){const down=pressed(pad,i),wasDown=!!previous[i];if(down)touched=true;if(down&&(!wasDown||[12,13,14,15].includes(i))&&shouldRepeat(i,now))action(i);previous[i]=down}const rawX=pad.axes?.[0]||0,rawY=pad.axes?.[1]||0,x=Math.abs(rawX)>AXIS_DEADZONE?Math.sign(rawX)*((Math.abs(rawX)-AXIS_DEADZONE)/(1-AXIS_DEADZONE)):0,y=Math.abs(rawY)>AXIS_DEADZONE?Math.sign(rawY)*((Math.abs(rawY)-AXIS_DEADZONE)/(1-AXIS_DEADZONE)):0;if(x||y)touched=true;if(touched){setControllerCursorHidden(true);emitControllerActivity({input:true,player:isPlayer()})}if(isPlayer())movePlayerMouse(x,y);else{if(x!==0&&lastAxis.x===0)action(x<0?BUTTONS.LEFT:BUTTONS.RIGHT);if(y!==0&&lastAxis.y===0)action(y<0?BUTTONS.UP:BUTTONS.DOWN)}lastAxis={x:x===0?0:Math.sign(x),y:y===0?0:Math.sign(y)};requestAnimationFrame(poll)}
window.addEventListener('gamepadconnected',e=>{activePad={index:e.gamepad.index,id:e.gamepad.id};previous=[];setStatus(`🎮 Controller detected · ${e.gamepad.id||'Gamepad'}`);emitControllerActivity({connected:true})});
window.addEventListener('gamepaddisconnected',e=>{if(!activePad||activePad.index===e.gamepad.index){activePad=null;setControllerCursorHidden(false);setStatus('🎮 Controller disconnected',false);window.dispatchEvent(new CustomEvent('controllerdisconnected'))}});
window.addEventListener('mousemove',()=>{if(controllerMode&&!isPlayer())setControllerCursorHidden(false)},{passive:true});
window.addEventListener('keydown',e=>{if(e.key==='Tab')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)&&!isPlayer())moveFocus(e.key.slice(5).toLowerCase())});
setStatus('🎮 Looking for controller…');requestAnimationFrame(poll);
